services:
  - type: web
    name: totp-backend
    env: python
    region: frankfurt  # Выберите ближайший к вам регион
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python -c "from app.init_app import init_app; init_app()" && \
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DATABASE_URL
        fromDatabase:
          name: totp-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: PYTHONPATH
        value: .
      - key: POSTGRES_SSLMODE
        value: require
    scaling:
      minInstances: 1
      maxInstances: 1

databases:
  - name: totp-db
    databaseName: totp_database
    user: totp_user
    plan: free
    ipAllowList: []
    postgresMajorVersion: 15 