"""add short_secret column

Revision ID: 2023_add_short_secret
Revises: f226bf9a8ec4
Create Date: 2024-03-21 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2023_add_short_secret'
down_revision = 'f226bf9a8ec4'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('totp_secrets', sa.Column('short_secret', sa.String(), nullable=True))
    op.create_index(op.f('ix_totp_secrets_short_secret'), 'totp_secrets', ['short_secret'], unique=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_totp_secrets_short_secret'), table_name='totp_secrets')
    op.drop_column('totp_secrets', 'short_secret')
    # ### end Alembic commands ### 