"""Add is_verified column to totp_secrets

Revision ID: f226bf9a8ec4
Revises: 
Create Date: 2025-05-28 06:03:58.800817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f226bf9a8ec4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('totp_secrets', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.drop_column('totp_secrets', 'created_at')
    op.drop_column('totp_secrets', 'name')
    op.drop_column('totp_secrets', 'issuer')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('totp_secrets', sa.Column('issuer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('totp_secrets', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('totp_secrets', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('totp_secrets', 'is_verified')
    # ### end Alembic commands ###
